[project]
requires-python = ">=3.11"
name = "aides-agri"
version = "0.1.0"
dependencies = [
  "django ~=5.1",
  "django-dsfr ~=2.1",
  "django-grist-loader ~=0.1",
  "django-htmx>=1.23.0",
  "psycopg[binary] ~=3.0",
  "requests ~=2.32",
]

[dependency-groups]
dev = [
  "djade",
  "django-browser-reload",
  "django-debug-toolbar",
  "ruff",
  "pytest",
  "pytest-cov",
  "pytest-django",
  "pytest-factoryboy",
  "requests-mock",
]
scalingo = [
  "gunicorn ~=23.0",
  "whitenoise ~=6.8",
]

[tool.coverage.run]
omit = ["**/tests/*"]

[tool.coverage.report]
show_missing = true
